name: oralsync
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.6.7
  flutter_screenutil: ^5.9.0
  dartz: ^0.10.1
  flutter_native_splash: ^2.3.7
  easy_localization: ^3.0.4
  dio: ^5.0.3
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.3.1
  flutter_spinkit: ^5.2.0
  flutter_holo_date_picker: ^1.1.3
  intl: ^0.18.1
  flutter_lazy_indexed_stack: ^0.0.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^4.0.0
  easy_image_viewer: ^1.4.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  flutter_switch: ^0.3.2
  page_transition: ^2.1.0
  url_launcher: ^6.2.5
  flutter_rating_bar: ^4.0.1
  top_snackbar_flutter: ^3.1.0
  flutter_staggered_animations: ^1.1.1
  percent_indicator: ^4.2.3
  animate_do: ^3.3.4
  json_serializable: ^6.8.0
  easy_stepper: ^0.8.5
  json_annotation: ^4.9.0
  firebase_core: ^2.27.0
  firebase_database: ^10.4.9
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
flutter:
  uses-material-design: true
  assets:
    - assets/auth/images/
    - assets/translations/
    - assets/student/images/
    - assets/student/
    - assets/test/

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
