name: oralsync
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.6.7
  flutter_screenutil: ^5.9.0
  dartz: ^0.10.1
  flutter_native_splash: ^2.3.7
  easy_localization: ^3.0.4
  dio: ^5.0.3
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.3.1
  flutter_spinkit: ^5.2.0
  flutter_holo_date_picker: ^1.1.3
  intl: ^0.18.1
  flutter_lazy_indexed_stack: ^0.0.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  easy_image_viewer: ^1.4.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/auth/images/
    - assets/translations/
    - assets/student/images/
    #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
