name: oralsync
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Firebase Configs
  firebase_core: ^2.27.0
  firebase_database: ^10.4.9
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19
  firebase_storage: ^11.6.9
  # as a state management
  flutter_bloc: ^8.1.4
  # for objects equality
  equatable: ^2.0.5
  # Service Locator
  get_it: ^7.6.7
  # to make ui responsive
  flutter_screenutil: ^5.9.0
  # Functional Programming
  dartz: ^0.10.1
  # localisation
  easy_localization: ^3.0.4
  intl: ^0.18.1
  # for http requests (APIs)
  dio: ^5.0.3
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  internet_connection_checker: ^1.0.0+1
  # local storage (primitive and non-primitive Data)
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  # to handle svg assets
  flutter_svg: ^2.0.9
  flutter_spinkit: ^5.2.0
  #  flutter_holo_date_picker: ^1.1.3
  # images
  image_picker: ^1.0.7
  easy_image_viewer: ^1.4.1
  # launch url
  url_launcher: ^6.2.5
  # ui
  flutter_lazy_indexed_stack: ^0.0.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^4.0.0
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  flutter_switch: ^0.3.2
  page_transition: ^2.1.0
  flutter_rating_bar: ^4.0.1
  top_snackbar_flutter: ^3.1.0
  flutter_staggered_animations: ^1.1.1
#  percent_indicator: ^4.2.3
  animate_do: ^3.3.4
  easy_stepper: ^0.8.5
  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  # icon and splash screen of OS
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
flutter:
  uses-material-design: true
  assets:
    - assets/auth/images/
    - assets/translations/
    - assets/student/images/
    - assets/student/
    - assets/test/
    - assets/configs/

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf

