// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG8lYtsAziGw-Xl2j6mjF7ELAG1DhhjOo',
    appId: '1:813886479686:web:89d317bb940ec56e151947',
    messagingSenderId: '813886479686',
    projectId: 'oral-sync',
    authDomain: 'oral-sync.firebaseapp.com',
    storageBucket: 'oral-sync.appspot.com',
    measurementId: 'G-2LZJB6ZJ7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChy03z4FGqQUmVmr-XnPytqO5a8hcVXMY',
    appId: '1:813886479686:android:26c7993187ce8cfa151947',
    messagingSenderId: '813886479686',
    projectId: 'oral-sync',
    storageBucket: 'oral-sync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjvlMhgeftZ07n-S1dDywePvUQ4SrBFXg',
    appId: '1:813886479686:ios:61a7e0ae93cb4b5d151947',
    messagingSenderId: '813886479686',
    projectId: 'oral-sync',
    storageBucket: 'oral-sync.appspot.com',
    iosBundleId: 'com.oralsync.oralsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG8lYtsAziGw-Xl2j6mjF7ELAG1DhhjOo',
    appId: '1:813886479686:web:7b378a8431e2a6b5151947',
    messagingSenderId: '813886479686',
    projectId: 'oral-sync',
    authDomain: 'oral-sync.firebaseapp.com',
    storageBucket: 'oral-sync.appspot.com',
    measurementId: 'G-K9EXY7C55K',
  );
}
